version: '3'
services:
  pihole:
    image: pihole-unbound
    container_name: pihole-unbound
    network_mode: host
    restart: always
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '67:67/udp'
      - '80:80/tcp'
      - '443:443/tcp'
   volumes:
      - '/mount/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
      - '/mount/pihole/etc-pihole:/etc/pihole'
      - '/mount/unbound:/etc/unbound'
    environment:
      TZ: 'Europe/Berlin'
      WEBPASSWORD: 'WEBPASSWORD'
      ServerIP: '192.168.178.60'
      REV_SERVER: 'true'
      REV_SERVER_DOMAIN: 'fritz.box'
      REV_SERVER_TARGET: '192.168.178.1'
      REV_SERVER_CIDR: '192.168.178.0/24'
      DNS1: 127.0.0.1#5335
      DNS2: 127.0.0.1#5335
      WEB_PORT: '8081'
